version: '3'
services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: mongodb://mongodb:27017/organizationdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:prod

  mongodb:
    image: mongo:latest
    container_name: nestjs_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: nestjs_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
